dhavalpurohit/admin-shop

- src/components/DropDownCommon/index.tsx
- src/pages/AddProduct/SingleProduct.tsx
- add product basic details UI
> feat: add product form ui

- package-lock.json
- package.json
- src/App.tsx
- src/components/Tables/TableTwo.tsx
- src/pages/AddProduct/BulkUpload.tsx
- src/pages/AddProduct/SingleProduct.tsx
- src/pages/AddProduct/stepperData/Additional.tsx
- src/pages/AddProduct/stepperData/BasicDetails.tsx
- src/pages/AddProduct/stepperData/Variants.tsx
- src/routes/index.tsx
> feat: bulk upload UI

- src/components/Tables/TableTwo.tsx
- single upload and bulk upload table ui
> feat: product table ui

- src/components/Sidebar/index.tsx
- src/images/common/search.svg
- src/pages/Banner/Table.tsx
- src/pages/Banner/index.tsx
- src/routes/index.tsx
- src/types/banner.ts
> feat: banner list ui

- src/components/DropDownCommon/index.tsx
- src/components/ProductCategoryDropdown/CategoryDropdown.tsx
- src/components/ProductCategoryDropdown/SubCategoryDropdown.tsx
- src/pages/AddProduct/BulkUpload.tsx
- src/pages/AddProduct/SingleProduct.tsx
- src/pages/AddProduct/stepperData/Additional.tsx
- src/pages/AddProduct/stepperData/BasicDetails.tsx
- src/pages/AddProduct/stepperData/Variants.tsx
- src/redux/slices/ProductSlice.ts
- src/services/Urls.ts
- src/services/api/ProductApi.ts
- src/types/category.ts
implemented basic form of add products
validations and api call pending
> implemented basic form of add products

- src/App.tsx
- src/common/ProtectedRoute/index.tsx
- src/components/Header/DropdownUser.tsx
- src/context/AuthContext/index.tsx
- src/layout/DefaultLayout.tsx
- src/pages/Authentication/SignIn.tsx
- src/routes/index.tsx
> feat:login implement

- src/routes/index.tsx
> fix: route issues fix

- src/pages/AddProduct/stepperData/BasicDetails.tsx
- src/pages/AddProduct/stepperData/Variants.tsx
-  add stock and status  checkbox  in add product
> feat: add checkbox in stock & status

- src/components/Header/DropdownUser.tsx
- src/main.tsx
- src/pages/AddProduct/SingleProduct.tsx
- src/pages/AddProduct/stepperData/BasicDetails.tsx
- src/pages/Authentication/SignIn.tsx
- src/routes/index.tsx
- src/services/http/commonService.ts
implemented add product single
> implemented add product single

- src/components/Tables/TableTwo.tsx
- src/redux/slices/ProductSlice.ts
- src/services/Urls.ts
- src/services/api/ProductApi.ts
- src/types/product.ts
> implemented product list

- src/pages/AddProduct/BulkUpload.tsx
> fixed download sample file

- src/common/ButtonLoader/index.tsx
- src/components/Tables/TableTwo.tsx
- src/pages/AddProduct/BulkUpload.tsx
- loader add in product listing page and download sample file button
> feat: loader upload

- src/components/DropDownCommon/index.tsx
- src/pages/Banner/AddBanner.tsx
- src/pages/Banner/Table.tsx
- src/pages/Order/Table.tsx
- src/routes/index.tsx
- src/types/banner.ts
- order filter and search
- add banner ui
> feat: banner add ui

- src/common/ButtonLoader/index.tsx
- src/common/Loader/index.tsx
- src/pages/Banner/AddBanner.tsx
- src/pages/Banner/Table.tsx
- src/redux/slices/bannerSlice.ts
- src/services/Urls.ts
- src/services/api/BannerApi.ts
- add banner form implement setup
> feat: add banner form implement

- src/common/Modal/index.tsx
- src/components/Tables/TableTwo.tsx
- src/pages/Banner/AddBanner.tsx
- src/pages/Banner/AddProductBanner.tsx
- src/pages/Banner/AddProductBannerModal.tsx
- src/pages/Banner/Table.tsx
- src/pages/Order/Table.tsx
> feat: add product modal

- src/components/Header/DropdownUser.tsx
- src/components/Tables/ProductTable.tsx
- src/pages/AddProduct/stepperData/BasicDetails.tsx
- src/pages/AddProduct/stepperData/Variants.tsx
- src/pages/Banner/AddBanner.tsx
> fix: issues

- src/pages/AddProduct/BulkUpload.tsx
> changed flow of sample file download

- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
- src/pages/Product/ViewSingleProduct.tsx
> fix: view and edit product

- src/pages/Product/BulkUpload.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
- src/redux/slices/ProductSlice.ts
> feat: fix update data

- src/pages/Product/SingleProduct.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
- src/pages/Product/stepperData/Variants.tsx
- src/redux/slices/ProductSlice.ts
- src/services/Urls.ts
- src/services/api/ProductApi.ts
> implemented filter changes

- src/pages/Product/SingleProduct.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
- add products options ui and implements
> feat: options ui and api implements

- src/pages/Product/SingleProduct.tsx
- src/pages/Product/ViewSingleProduct.tsx
loader add ni new product add and view product
> fix: loader in product

- src/pages/Banner/ViewBanner.tsx
- src/pages/Product/SingleProduct.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
- src/pages/Product/UpdateProduct/stepperData/Variants.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
- src/pages/Product/stepperData/Variants.tsx
- src/services/Urls.ts
> fix: bug fix

- src/pages/Product/SingleProduct.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
fix: set default vandor product id
> fix: vandor product id default set

- src/components/DropDownCommon/index.tsx
- src/pages/Product/SingleProduct.tsx
- src/pages/Product/UpdateProduct/index.tsx
> fix: update issues

- src/components/ProductCategoryDropdown/CategoryDropdown.tsx
- src/components/ProductCategoryDropdown/SubCategoryDropdown.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
- src/pages/Product/stepperData/BasicDetails.tsx
> fix: brand list

- src/components/ProductCategoryDropdown/CategoryDropdown.tsx
- src/components/ProductCategoryDropdown/SubCategoryDropdown.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/UpdateProduct/stepperData/BasicDetails.tsx
fixed the category related issue
> fixed the category related issue

- src/pages/Product/SingleProduct.tsx
- src/pages/Product/UpdateProduct/index.tsx
- src/pages/Product/stepperData/Variants.tsx
> Fixed rendering of options
